### ISSUE TITLE
cannot create proposals in necdao schemes on rinkeby

### ISSUE THREAD

**Issue by jellegerbrandy** [daostack/nectardao#13]
I cannot create a proposal in either the contributionreward scheme or the genericschemes.

Here is an example of a failing transaction: 
https://rinkeby.etherscan.io/tx/0xfcab7beb8b2558a10afb33a15c48501cffa099d63010f0b6e3085ab3048af376

https://rinkeby.etherscan.io/tx/0x49e2fcdce369e1f4b902451b1d77021b447f6e0275f0dd299742e8bdafab69c4

It says "Fail with error ' not active yet'"

**Comment by jellegerbrandy** [comment]
(our info page says that it _is_ active: https://alchemy-staging-rinkeby.herokuapp.com/dao/0xb48a33ad7342d2541113f4b89d259062ec149b76/scheme/0x7cd099a8b836ad7e964bbfa087f76038e95d1794b58a3df5d4c70d9f2289116d/info/)

**Comment by orenyodfat** [comment]
yes. because the governance  only starts at 16:00 GMT+3 

alchemy should be aware of that 
https://github.com/daostack/alchemy/issues/737
